float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: Glass
    disabled: false
    docker_tag: ann-benchmarks-glass
    module: ann_benchmarks.algorithms.glass
    name: glass
    run_groups:
      HNSW:
        args:
          L: 200
          R: [4]
          level: [1]
        query_args: [[120, 200, 400, 600, 800]]
