float:
  any:
  - base_args: ['@metric']
    constructor: Symqg
    disabled: false
    docker_tag: ann-benchmarks-symqg
    module: ann_benchmarks.algorithms.symqg
    name: symqg
    run_groups:
      M-16:
        arg_groups: [{M: 16, efConstruction: 200}]
        args: {}
        query_args: [[120, 200, 400, 600, 800]]
